### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by skw0716** [KaiyuanZh/OrthogLinearBackdoor#4]
hi,I encountered an error while using files in your ckpt directory, but the model I trained myself would not have this error. However, the data from my trained model does not seem to match the original text. Can you provide more detailed information?

`
Traceback (most recent call last):
  File "backdoor_mitigation.py", line 855, in <module>
    main(args)
  File "backdoor_mitigation.py", line 762, in main
    model = torch.load(model_filepath, map_location="cpu")
  File "/home/chenshuhong/anaconda3/envs/zxj_orth/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/chenshuhong/anaconda3/envs/zxj_orth/lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`

**Comment by KaiyuanZh** [comment]
Hi @skw0716, I do not have full details about how your code is being run or configured. From my experience, this issue might occur if the file was saved using a different Python or PyTorch version. Please double-check that your file aligns with the configurations specified in the `environment.yml`.
